### ISSUE TITLE
Standardize JSON for recipes

### ISSUE THREAD

**Issue by lmidang** [cse110-fa21-group33/cse110-fa21-group33#36]

**Comment by Cole-Rindal** [comment]
Units Standards

Non Specific:
Pinch
Splash
Drop
Quantity (2 apples)

Volume:
c = cups
pt = pints
qt = quarts
gal = gallons
tsp = teaspoon
tbsp = tablespoon
fl oz = fluid ounce
mL = milliliter
L = liter

Weight:
g = grams
kg = kilograms
oz = ounces
lbs = pounds

Length:
mm = millimeter
cm = centimeter
m = meter
in = inch

Temperature:
°F = degrees Fahrenheit
°C = degrees Celsius
